-- One-time load of the company setup from RS 2026.xls and Payroll Details october26.xls (prepared 2026-10-10).
-- Runs only on an empty chart of accounts, so it does nothing once accounts exist.
do $load$
begin
  if exists (select 1 from accounts) then
    raise notice 'rs2026 setup: accounts already exist, skipped';
    return;
  end if;
  insert into projects (id, code, name, type, unit, status, description, is_office) values ('office', 'Office', 'Office', 'Administrative', 'Office', 'Active', 'Head office, general & administrative', true) on conflict do nothing;
  insert into projects (id, code, name, status, gl_suffix) values ('ph-b1302', 'PH-B1302', 'PH-B1302', 'Active', 1) on conflict do nothing;
  insert into projects (id, code, name, status, gl_suffix) values ('cs-ch2505', 'CS-CH2505', 'CS-CH2505', 'Active', 2) on conflict do nothing;
  insert into projects (id, code, name, status, gl_suffix) values ('ph-b1332', 'PH-B1332', 'PH-B1332', 'Active', 3) on conflict do nothing;
  insert into projects (id, code, name, status, gl_suffix) values ('ph-1524', 'PH-1524', 'PH-1524', 'Active', 4) on conflict do nothing;
  insert into projects (id, code, name, status, gl_suffix) values ('latin-alamin', 'LATIN-ALAMIN', 'LATIN-ALAMIN', 'Active', 5) on conflict do nothing;
  insert into projects (id, code, name, status, gl_suffix) values ('smouha-desoqy', 'Smouha-Desoqy', 'Smouha-Desoqy', 'Active', 6) on conflict do nothing;
  insert into departments (id, code, name) values ('adm', 'ADM', 'Admin & HR') on conflict do nothing;
  insert into departments (id, code, name) values ('eng', 'ENG', 'Engineering') on conflict do nothing;
  insert into departments (id, code, name) values ('fin', 'FIN', 'Finance') on conflict do nothing;
  insert into departments (id, code, name) values ('mgt', 'MGT', 'Management') on conflict do nothing;
  insert into departments (id, code, name) values ('snm', 'S&M', 'Sales & Marketing') on conflict do nothing;
  insert into parties (id, code, type, name, notes) values ('vc0001', 'VC0001', 'vendor', 'Cash-Office', 'From RS 2026.xls') on conflict do nothing;
  insert into parties (id, code, type, name, notes) values ('vc0002', 'VC0002', 'vendor', 'Cash-Adel', 'From RS 2026.xls') on conflict do nothing;
  insert into parties (id, code, type, name, notes) values ('vc0003', 'VC0003', 'vendor', 'Cash-Youssef', 'From RS 2026.xls') on conflict do nothing;
  insert into parties (id, code, type, name, notes) values ('vc0004', 'VC0004', 'vendor', 'Cash-Haitham', 'From RS 2026.xls') on conflict do nothing;
  insert into parties (id, code, type, name, notes) values ('vc0005', 'VC0005', 'vendor', 'Cash-Marwan', 'From RS 2026.xls') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A100', 'Current assets', 'asset', null, false, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A110', 'Cash – office safe', 'asset', 'A100', true, true, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A120', 'Main bank account', 'asset', 'A100', true, true, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A130', 'Accounts receivable – customers', 'asset', 'A100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A140', 'Input VAT', 'asset', 'A100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A150', 'WHT deducted by customers', 'asset', 'A100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A160', 'Staff advances & custody', 'asset', 'A100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A170', 'Prepaid expenses & deposits', 'asset', 'A100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A200', 'Non-current assets', 'asset', null, false, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A210', 'Property & equipment', 'asset', 'A200', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('A219', 'Accumulated depreciation', 'asset', 'A200', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L100', 'Current liabilities', 'liability', null, false, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L110', 'Accounts payable – vendors', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L120', 'Retention payable', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L130', 'Customer advances', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L140', 'Output VAT', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L150', 'WHT payable', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L160', 'Social insurance payable – payroll', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L165', 'Contractors'' social insurance payable', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L170', 'Salary tax payable', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L180', 'Salaries payable', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('L190', 'Accrued expenses', 'liability', 'L100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('Q100', 'Equity', 'equity', null, false, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('Q110', 'Partners'' capital & funding', 'equity', 'Q100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('Q120', 'Retained earnings', 'equity', 'Q100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('R100', 'Revenue', 'revenue', null, false, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('R110', 'Project revenue', 'revenue', 'R100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('R120', 'Unit sales revenue', 'revenue', 'R100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_bank, is_system) values ('R190', 'Other income', 'revenue', 'R100', true, false, true) on conflict do nothing;
  insert into accounts (code, name, type, postable, project_id) values ('10000', 'Office expenses', 'expense', false, 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, is_system, cost_type, project_id) values ('11010', 'Social insurance – company share', 'expense', '10000', true, true, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, postable, project_id) values ('20000-1', 'PH-B1302 project costs', 'expense', false, 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, postable, project_id) values ('20000-2', 'CS-CH2505 project costs', 'expense', false, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, postable, project_id) values ('20000-3', 'PH-B1332 project costs', 'expense', false, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, postable, project_id) values ('20000-4', 'PH-1524 project costs', 'expense', false, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, postable, project_id) values ('20000-5', 'LATIN-ALAMIN project costs', 'expense', false, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, postable, project_id) values ('20000-6', 'Smouha-Desoqy project costs', 'expense', false, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('11001', 'الراتب الاساسي', 'expense', '10000', true, 450000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('11002', 'عمالة غير منتظمة', 'expense', '10000', true, 5000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('11003', 'الانتقالات الشخصية', 'expense', '10000', true, 2000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('11004', 'أكراميات', 'expense', '10000', true, 2000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('12001', 'أيجار المكاتب', 'expense', '10000', true, 375000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('12002', 'رسوم الجراج', 'expense', '10000', true, 30000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('13001', 'مستلزمات الضيافة', 'expense', '10000', true, 18000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('13002', 'الادوات المكتبية', 'expense', '10000', true, 6000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('13003', 'المعدات المكتبية', 'expense', '10000', true, 150000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('14001', 'الرسوم القانونية و المحاسبية', 'expense', '10000', true, 20000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('14002', 'رسوم التليفون والأنترنت', 'expense', '10000', true, 4200.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('14003', 'رسوم الكهرباء و المياه و الغاز', 'expense', '10000', true, 10000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('14004', 'مصاريف التسويق', 'expense', '10000', true, 60000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('19001', 'تشطيب المكتب', 'expense', '10000', true, null, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('19002', 'صيانة المكتب', 'expense', '10000', true, 10000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('21001', 'الرسم الهندسي', 'expense', '10000', true, 30000.0, 'Opex', 'office') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable) values ('90000', 'دفعات مقدمة', 'asset', 'A100', true) on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('21001-1', 'الرسم الهندسي', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22001-1', 'تعديلات معمارية', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22002-1', 'تأسيس سباكة', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22003-1', 'تأسيس كهرباء', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22004-1', 'أعمال تأسيس التكييفات', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22005-1', 'أعمال التهوية', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23001-1', 'توريد و تركيب الجيبسون بورد', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24001-1', 'مستلزمات كهرباء', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24002-1', 'مستلزمات سباكة', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24003-1', 'مستلزمات نقاشة', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24004-1', 'مستلزمات سيراميك', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23002-1', 'توريد و تركيب الالوميتال', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23003-1', 'توريد و تركيب HDF', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23004-1', 'توريد و تركيب الرخام', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23005-1', 'توريد و تركيب زجاج', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25001-1', 'أعمال النجارة', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25002-1', 'أعمال الفيوتك', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25003-1', 'أعمال CNC', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25004-1', 'توريد و تركيب العفش', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26001-1', 'مصنعيات كهرباء', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26002-1', 'مصنعيات سباكة', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26003-1', 'مصنعيات سيراميك', 'expense', '20000-1', true, null, 'Capex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26004-1', 'مصنعيات محارة', 'expense', '20000-1', true, null, 'Capex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26005-1', 'مصنعيات نقاشة', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26006-1', 'مصنعيات أستورجي', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26007-1', 'مصنعيات نجارة', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26008-1', 'عمالة', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('27001-1', 'تصاريح', 'expense', '20000-1', true, null, 'Opex', 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28001-1', 'نثريات الموقع', 'expense', '20000-1', true, null, null, 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28002-1', 'مشتريات', 'expense', '20000-1', true, null, null, 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28003-1', 'رمل', 'expense', '20000-1', true, null, null, 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28006-1', 'توريد وتركيب الباركية', 'expense', '20000-1', true, null, null, 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28004-1', 'أسمنت', 'expense', '20000-1', true, null, null, 'ph-b1302') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('21001-2', 'الرسم الهندسي', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22001-2', 'تعديلات معمارية', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22002-2', 'تأسيس سباكة', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22003-2', 'تأسيس كهرباء', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22004-2', 'أعمال تأسيس التكييفات', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22005-2', 'أعمال التهوية', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23001-2', 'توريد و تركيب الجيبسون بورد', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24001-2', 'مستلزمات كهرباء', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24002-2', 'مستلزمات سباكة', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24003-2', 'مستلزمات نقاشة', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24004-2', 'مستلزمات سيراميك', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23002-2', 'توريد و تركيب الالوميتال', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23003-2', 'توريد و تركيب HDF', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23004-2', 'توريد و تركيب الرخام', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23005-2', 'توريد و تركيب زجاج', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25001-2', 'أعمال النجارة', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25002-2', 'أعمال الفيوتك', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25003-2', 'أعمال CNC', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25004-2', 'توريد و تركيب العفش', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26001-2', 'مصنعيات كهرباء', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26002-2', 'مصنعيات سباكة', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26003-2', 'مصنعيات سيراميك', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26004-2', 'مصنعيات محارة', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26005-2', 'مصنعيات نقاشة', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26006-2', 'مصنعيات أستورجي', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26007-2', 'مصنعيات نجارة', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26008-2', 'عمالة', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('27001-2', 'تصاريح', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28001-2', 'نثريات الموقع', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28002-2', 'مشتريات', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28003-2', 'رمل', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28004-2', 'أسمنت', 'expense', '20000-2', true, null, null, 'cs-ch2505') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('21001-3', 'الرسم الهندسي', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22001-3', 'تعديلات معمارية', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22002-3', 'تأسيس سباكة', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22003-3', 'تأسيس كهرباء', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22004-3', 'أعمال تأسيس التكييفات', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22005-3', 'أعمال التهوية', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23001-3', 'توريد و تركيب الجيبسون بورد', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24001-3', 'مستلزمات كهرباء', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24002-3', 'مستلزمات سباكة', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24003-3', 'مستلزمات نقاشة', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24004-3', 'مستلزمات سيراميك', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23002-3', 'توريد و تركيب الالوميتال', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23003-3', 'توريد و تركيب HDF', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23004-3', 'توريد و تركيب الرخام', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23005-3', 'توريد و تركيب زجاج', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25001-3', 'أعمال النجارة', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25002-3', 'أعمال الفيوتك', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25003-3', 'أعمال CNC', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25004-3', 'توريد و تركيب العفش', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26001-3', 'مصنعيات كهرباء', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26002-3', 'مصنعيات سباكة', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26003-3', 'مصنعيات سيراميك', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26004-3', 'مصنعيات محارة', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26005-3', 'مصنعيات نقاشة', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26006-3', 'مصنعيات أستورجي', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26007-3', 'مصنعيات نجارة', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26008-3', 'عمالة', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('27001-3', 'تصاريح', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28001-3', 'نثريات الموقع', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28002-3', 'مشتريات', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28003-3', 'رمل', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28004-3', 'أسمنت', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28005-3', 'تشوين', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28007-3', 'توريد وتركيب الباركية', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28006-3', 'ردم', 'expense', '20000-3', true, null, null, 'ph-b1332') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('21001-4', 'الرسم الهندسي', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22001-4', 'تعديلات معمارية', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22002-4', 'تأسيس سباكة', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22003-4', 'تأسيس كهرباء', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22004-4', 'أعمال تأسيس التكييفات', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22005-4', 'أعمال التهوية', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23001-4', 'توريد و تركيب الجيبسون بورد', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24001-4', 'مستلزمات كهرباء', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24002-4', 'مستلزمات سباكة', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24003-4', 'مستلزمات نقاشة', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24004-4', 'مستلزمات سيراميك', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23002-4', 'توريد و تركيب الالوميتال', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23003-4', 'توريد و تركيب HDF', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23004-4', 'توريد و تركيب الرخام', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23005-4', 'توريد و تركيب زجاج', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25001-4', 'أعمال النجارة', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25002-4', 'أعمال الفيوتك', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25003-4', 'أعمال CNC', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25004-4', 'توريد و تركيب العفش', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26001-4', 'مصنعيات كهرباء', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26002-4', 'مصنعيات سباكة', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26003-4', 'مصنعيات سيراميك', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26004-4', 'مصنعيات محارة', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26005-4', 'مصنعيات نقاشة', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26006-4', 'مصنعيات أستورجي', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26007-4', 'مصنعيات نجارة', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26008-4', 'عمالة', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('27001-4', 'تصاريح', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28001-4', 'نثريات الموقع', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28002-4', 'مشتريات', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28003-4', 'رمل', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28004-4', 'أسمنت', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28005-4', 'تشوين', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28006-4', 'ردم', 'expense', '20000-4', true, null, null, 'ph-1524') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('21001-5', 'الرسم الهندسي', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22001-5', 'تعديلات معمارية', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22002-5', 'تأسيس سباكة', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22003-5', 'تأسيس كهرباء', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22004-5', 'أعمال تأسيس التكييفات', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22005-5', 'أعمال التهوية', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23001-5', 'توريد و تركيب الجيبسون بورد', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24001-5', 'مستلزمات كهرباء', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24002-5', 'مستلزمات سباكة', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24003-5', 'مستلزمات نقاشة', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24004-5', 'مستلزمات سيراميك', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23002-5', 'توريد و تركيب الالوميتال', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23003-5', 'توريد و تركيب HDF', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23004-5', 'توريد و تركيب الرخام', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23005-5', 'توريد و تركيب زجاج', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25001-5', 'أعمال النجارة', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25002-5', 'أعمال الفيوتك', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25003-5', 'أعمال CNC', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25004-5', 'توريد و تركيب العفش', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26001-5', 'مصنعيات كهرباء', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26002-5', 'مصنعيات سباكة', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26003-5', 'مصنعيات سيراميك', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26004-5', 'مصنعيات محارة', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26005-5', 'مصنعيات نقاشة', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26006-5', 'مصنعيات أستورجي', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26007-5', 'مصنعيات نجارة', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26008-5', 'عمالة', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('27001-5', 'تصاريح', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28001-5', 'نثريات الموقع', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28002-5', 'مشتريات', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28003-5', 'رمل', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28004-5', 'أسمنت', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28005-5', 'تشوين', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28006-5', 'ردم', 'expense', '20000-5', true, null, null, 'latin-alamin') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('21001-6', 'الرسم الهندسي', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22001-6', 'تعديلات معمارية', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22002-6', 'تأسيس سباكة', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22003-6', 'تأسيس كهرباء', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22004-6', 'أعمال تأسيس التكييفات', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('22005-6', 'أعمال التهوية', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23001-6', 'توريد و تركيب الجيبسون بورد', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24001-6', 'مستلزمات كهرباء', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24002-6', 'مستلزمات سباكة', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24003-6', 'مستلزمات نقاشة', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('24004-6', 'مستلزمات سيراميك', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23002-6', 'توريد و تركيب الالوميتال', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23003-6', 'توريد و تركيب HDF', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23004-6', 'توريد و تركيب الرخام', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23005-6', 'توريد و تركيب زجاج', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('23006-6', 'اعمال الدهانات', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25001-6', 'أعمال النجارة', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25002-6', 'أعمال الفيوتك', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25003-6', 'أعمال CNC', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('25004-6', 'توريد و تركيب العفش', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26001-6', 'مصنعيات كهرباء', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26002-6', 'مصنعيات سباكة', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26003-6', 'مصنعيات سيراميك', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26004-6', 'مصنعيات محارة', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26005-6', 'مصنعيات نقاشة', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26006-6', 'مصنعيات أستورجي', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26007-6', 'مصنعيات نجارة', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('26008-6', 'عمالة', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('27001-6', 'تصاريح', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28001-6', 'نثريات الموقع', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28002-6', 'مشتريات', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28003-6', 'رمل', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28004-6', 'أسمنت', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28005-6', 'تشوين', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  insert into accounts (code, name, type, parent, postable, budget, cost_type, project_id) values ('28006-6', 'ردم', 'expense', '20000-6', true, null, null, 'smouha-desoqy') on conflict do nothing;
  update settings set account_map = '{"ap": "L110", "ar": "A130", "dpAdv": "90000", "empAdv": "A160", "retPay": "L120", "salExp": "11001", "salPay": "L180", "siPay": "L165", "socExp": "11010", "socPay": "L160", "taxPay": "L170", "vatIn": "A140", "vatOut": "L140", "whtPay": "L150", "whtRec": "A150"}'::jsonb where id = 1 and account_map = '{}'::jsonb;
  update settings set cats = '{"service":["Design only","Fit-out / execution","Design & build","Supervision"],"type":["Residential","Commercial","Hospitality","Administrative"],"unit":["Penthouse","Chalet","Villa","Apartment","Office"]}'::jsonb where id = 1 and cats = '{}'::jsonb;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1001', '1001', 'Zeyad Essam Ahmed', 'Accounting', 'fin', '2026-06-22', 7000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1002', '1002', 'Hana Yasser Ibrahim Awad', 'Admin Office', 'adm', '2026-06-02', 5000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1003', '1003', 'Farah Elsayed Yakout', 'Junior 3D Engineer', 'eng', '2026-06-25', 8000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1004', '1004', 'Youssef Abdel Hameed Abdel Ghany', 'Junior 3D Engineer', 'eng', '2026-06-21', 3000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1005', '1005', 'Malak Mahmoud Ali Hassan', 'Junior 3D Engineer', 'eng', '2026-07-12', 7000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1006', '1006', 'Ali Mohamed Ali', 'Junior 3D Engineer', 'eng', '2026-07-12', 7000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1007', '1007', 'Mohamed Hassan Ahmed', 'Junior 3D Engineer', 'eng', '2026-07-12', 7000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1008', '1008', 'Heba Saaied Shebl', 'Office Boy', 'adm', '2026-07-16', 5000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1009', '1009', 'Saaied Sleem', 'Site Supervisor', 'eng', null, 10000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1010', '1010', 'Abdullah fayed', 'Junior 3D Engineer', 'eng', '2026-09-05', 22000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1011', '1011', 'Ezz', 'Junior 3D Engineer', 'eng', null, 2000.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1012', '1012', 'shabban', 'Site Labor', 'eng', null, 0.0, 0, 0, true) on conflict do nothing;
  insert into employees (id, code, name, job_title, dept_id, hire_date, basic, allowances, insurable, active) values ('emp-1013', '1013', 'Mohamed Ali Dsoqy', 'Engineer', 'eng', null, 0.0, 0, 0, true) on conflict do nothing;
end
$load$;
